### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [kumajelly/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. The font-weight property is also shared by several elements, so you can simplify it further like

```css
h2, h3, .cost {
  font-weight: bold;
}
```
